services:
  php:
    build: ./docker
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    user: 1000:www-data
    depends_on:
      - database
  database:
    image: mariadb:11.6
    ports:
      - ${DB_PORT}:3306
    environment:
      - MARIADB_HOST=${DB_HOST}
      - MARIADB_PORT=${DB_PORT}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_CHARSET=${DB_CHARSET}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: ['mariadbd', '--character-set-server=${DB_CHARSET}', '--collation-server=${DB_CHARSET}_unicode_ci']
    volumes:
      - app_db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - database

volumes:
  app_db:
    driver: local