services:
  php:
    build: ./docker
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    user: 1000:www-data
  database:
    image: mariadb:11.6
    ports:
      - ${DB_PORT}:3306
    environment:
      - MARIADB_HOST=${DB_HOST}
      - MARIADB_PORT=${DB_PORT}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_CHARSET=${DB_CHARSET}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: ['mariadbd', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMS_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80